- asb-ballerina/Dependencies.toml
- gradle.properties
> Bump dependency versions to ballerina beta2
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Bump dependency versions for Ballerina SLBeta2

- asb-ballerina/Dependencies.toml
- asb-ballerina/Package.md
- Bump version to slbeta3 in Dependencies.toml and Package.md
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 11
Ballerina SLBeta3-SNAPSHOT
> Bump versions for slbeta3 in master branch

- asb-ballerina/Dependencies.toml
- gradle.properties
$title
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 11
Ballerina SLBeta3
> Bump dependency versions

- asb-ballerina/init.bal
- asb-native/src/main/java/org/ballerinalang/asb/ASBConstants.java
- asb-native/src/main/java/org/ballerinalang/asb/ASBUtils.java
- asb-native/src/main/java/org/ballerinalang/asb/MessageDispatcher.java
- asb-native/src/main/java/org/ballerinalang/asb/ModuleUtils.java
- asb-native/src/main/java/org/ballerinalang/asb/connection/ConnectionUtils.java
- gradle.properties
- https://github.com/wso2-enterprise/choreo/issues/7857
- Remove hardcoded Module detail in java code
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
-
JDK 11
Ballerina SLBeta3
> Remove hardcoded Module detail in java code

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- README.md
- asb-ballerina/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> Add slbeta4 migration changes

- gradle.properties
- Bump ballerinaLangVersion to `2.0.0-beta.4-20211027-131700-08f09d04`
> Bump ballerinaLangVersion to 2.0.0-beta.4-20211027-131700-08f09d04

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/Package.md
- gradle.properties
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
> Prepare for 2.1.0 release with SLBeta6

- .github/workflows/daily-build.yml
> Fix curl command in daily build.yaml

- asb-ballerina/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
> Re-generate Dependencies.toml with latest pack

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/Package.md
- gradle.properties
prepare connector for `2201.0.0` release
> prepare connector for `2201.0.0` release

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-native/build.gradle
- gradle.properties
$subject
Fixes 
https://github.com/ballerina-platform/ballerina-extended-library/issues/316
- Remove runtime dependency from native jar dependency
* Ballerina Version: 2201.0.0
* Operating System: Ubuntu
* Java SDK: 11
> Remove runtime dependency from native dependency jar

- asb-ballerina/Ballerina.toml
- asb-native/build.gradle
Update platform dependencies
Fixes # (issue)
- https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/100
> Update platform dependencies

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/Module.md
- asb-ballerina/Package.md
- asb-ballerina/config-types.bal
- asb-ballerina/messageReceiver.bal
- asb-ballerina/messageSender.bal
- asb-ballerina/samples/abandon_message_from_queue.bal
- asb-ballerina/samples/abandon_message_from_subscription.bal
- asb-ballerina/samples/complete_message_from_queue.bal
- asb-ballerina/samples/complete_message_from_subscription.bal
- asb-ballerina/samples/deadletter_from_queue.bal
- asb-ballerina/samples/deadletter_from_subscription.bal
- asb-ballerina/samples/defer_from_queue.bal
- asb-ballerina/samples/defer_from_subscription.bal
- asb-ballerina/samples/renew_lock_on_message_from_queue.bal
- asb-ballerina/samples/renew_lock_on_message_from_subscription.bal
- asb-ballerina/samples/send_and_receive_batch_from_queue.bal
- asb-ballerina/samples/send_and_receive_message_from_queue.bal
- asb-ballerina/samples/send_batch_to_topic_and_receive_from_subscription.bal
- asb-ballerina/samples/send_to_topic_and_receive_from_subscription.bal
- asb-ballerina/tests/asb_test.bal
- gradle.properties
Revamp connector 
related [#14865](https://github.com/wso2-enterprise/choreo/issues/14865)
* Ballerina Version: Ballerina 2201.2.0
* Operating System: Ubuntu
* Java SDK: Java 11
> Revamp connector #14865

- asb-ballerina/config-types.bal
Reverts ballerina-platform/module-ballerinax-azure-service-bus#112
> Revert "Update config-types.bal"

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/Package.md
- gradle.properties
> Bump bal version to 2201.2.1

- README.md
- asb-ballerina/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/Package.md
- gradle.properties
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- asb-ballerina/Ballerina.toml
- gradle.properties
> [Main] Updating the version of the connector to 3.0.2

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- gradle.properties
> [2201.3.x] Bump the version to 3.0.3

- .github/workflows/ci.yml
- Update bal version to 2201.3.1 in ci.yaml
> [2201.3.1] Update bal version to 2201.3.1 in ci.yaml

- asb-ballerina/Ballerina.toml
- asb-ballerina/message.bal
- asb-ballerina/tests/asb_test.bal
- asb-ballerina/utils.bal
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- gradle.properties
> $subject
As per the discussion we had with @abeykoon and @SanduDS I have sent the PR on behalf of Connector team.
Referred to service bus documentation [1] for this change.
[1] - https://learn.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties#message-properties
Fixes [#19457](https://github.com/wso2-enterprise/choreo/issues/19457)
- Update value type of the application-properties in `asb:Message`
* Ballerina Version: Ballerina 2201.3.x
* Operating System: Ubuntu
* Java SDK: Open JDK 11
> Update value type of the application properties to `map<anydata>` in `asb:Message`

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/commons.bal
- asb-ballerina/messageReceiver.bal
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBConstants.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBUtils.java
- gradle.properties
> $subject
Fixes: [#4225](https://github.com/ballerina-platform/ballerina-standard-library/issues/4225)
- Add AMQP retry configuration to `asb:MessageReceiver`
* Ballerina Version: 2201.3.2
* Operating System: Linux
* Java SDK: OpenJDK 11
> [2201.3.x] Add AMQP retry configuration to `asb:MessageReceiver`

- asb-ballerina/Ballerina.toml
- asb-ballerina/commons.bal
- asb-ballerina/messageSender.bal
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/sender/MessageSender.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBUtils.java
- gradle.properties
> $subject
Fixes [#4249](https://github.com/ballerina-platform/ballerina-standard-library/issues/4249)
- Add AMQP retry configuration to `asb:MessageSender`
* Ballerina Version: 2201.3.2
* Operating System: Linux
* Java SDK: OpenJDK 11
> Add AMQP retry configuration to `asb:MessageSender`

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-ballerina/commons.bal
- asb-ballerina/messageSender.bal
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/sender/MessageSender.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBUtils.java
- gradle.properties
> $subject
Fixes [#4249](https://github.com/ballerina-platform/ballerina-standard-library/issues/4249)
- Add AMQP retry configuration to `asb:MessageSender`
* Ballerina Version: 2201.3.2
* Operating System: Linux
* Java SDK: OpenJDK 11
> [2201.3.x] Add AMQP retry configuration to `asb:MessageSender`

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- gradle.properties
- Fix https://github.com/wso2-enterprise/choreo/issues/19641
> [2201.3.x] Fix message array size for receiveBatch

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- gradle.properties
> Prepare for 3.2.2 patch release

- asb-ballerina/tests/asb_test.bal
> Fix intermittent test failures

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- gradle.properties
- Bump connector version to `3.2.3`
> Bump version to 3.2.3

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- asb-native/build.gradle
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/sender/MessageSender.java
- gradle.properties
$subject.
- Fixed a security vulnerability caused by an older log4j version
* Java SDK:
> Replace log4j with slf4j and avoid packing the logging artficats into the native jar

- asb-ballerina/Ballerina.toml
- asb-ballerina/Dependencies.toml
- gradle.properties
> [2201.3.x] Bump version to 3.2.4

- asb-native/build.gradle
- asb-native/src/main/java/module-info.java
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/sender/MessageSender.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBUtils.java
- gradle.properties
> Replace log4j with slf4j and, avoid log dependency getting packed into the native jar

- gradle.properties
$subject from 7.13.1 to 7.14.1
- Updated Java SDK version
* Java SDK:
> Update java SDK version

- asb-native/src/main/resources/META-INF/native-image/org.ballerinax/asb-native/native-image.properties
> Initialize `org.slf4j` classes at GraalVM native-image build-time

- asb-native/src/main/resources/META-INF/native-image/org.ballerinax/asb-native/reflect-config.json
> Add missing reflection configs for GraalVM build

- .github/workflows/pull-request.yml
$subject as we cannot run tests sent from the forked repos, as the tests require ASB auth tokens which are configured as repo secrets
> Disable running tests if the PR is sent from a forked repository

- asb-ballerina/Ballerina.toml
- asb-ballerina/Package.md
- gradle.properties
> Update with `graalvmCompatible` property

- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
> Update setup ballerina action in PR build

- asb-ballerina/Ballerina.toml
- asb-native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- asb-native/src/main/java/org/ballerinax/asb/util/ASBConstants.java
- gradle.properties
This should fix https://github.com/wso2-enterprise/internal-support-ballerina/issues/380#issuecomment-1656695729
* Java SDK:
> [2201.4.x] Fix memory leak in receiver client

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
> Fix working directory in workflows

- .github/workflows/dev-stg-release.yml
$subject to avoid releasing the module on unexpected versions.
> Set Ballerina release version to 2201.7.0

- .github/workflows/build-with-bal-test-native.yml
$subject as the gradle build now requires the Ballerina environment.
> Setup Ballerina in GraalVM check

- ballerina/Ballerina.toml
- gradle.properties
- native/src/main/java/org/ballerinax/asb/receiver/MessageReceiver.java
- native/src/main/java/org/ballerinax/asb/util/ASBConstants.java
This should fix https://github.com/wso2-enterprise/internal-support-ballerina/issues/380#issuecomment-1656695729
* Java SDK:
> [2201.7.x] Fix memory leak in receiver client

- .trivyignore
- gradle.properties
$subject with bumping the version of azure service bus. 
Related to https://github.com/ballerina-platform/ballerina-extended-library/issues/549
- Ballerina Version: 2201.7.0
- Operating System: macOS 13.4.1
- Java SDK: openjdk 11.0.20
> Fix vulnerable java dependencies

- examples/admin/delete_topic.bal
In ASB admin example "delete-topic",incorrect method was invoked instead of the correct method deleteTopic().
> Fix issue in example-delete-topic

- ballerina/tests/asb_admin_negative_test.bal
Revise test cases to align with the ASB bump 7.14.3
> Revise test cases to align with the ASB bump 7.14.3

- ballerina/Ballerina.toml
- gradle.properties
$subject.
Fixes # (issue)
* Java SDK:
> Bump minor version for 3.6.0 release

- ballerina/receiver.bal
- ballerina/sender.bal
- ballerina/tests/asb_admin_tests.bal
- ballerina/tests/asb_sender_receiver_tests.bal
- examples/admin/create_rule_with_with_included_options.bal
- examples/admin/update_rule_with_included_options.bal
Fix ASB Connector Compatibility Issues for Ballerina Update 2201.8.0
Fixes # (issue)
- Fix Type Mismatch Error
- Fix the issue:Disallow annotations with mutable objects
- Fix ASB compatibility Issues for U8
> Fix ASB compatibility Issues for U8

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
> Exclude examples build in trivy scans

- ballerina/Ballerina.toml
- gradle.properties
> Patch version bump

- ballerina/Dependencies.toml
- ballerina/tests/asb_sender_receiver_negative_tests.bal
> Migrate std:regex to lang.regexp

- .github/workflows/trivy-scan.yml
Resolves https://github.com/ballerina-platform/ballerina-library/issues/6367
> Use centralized workflow for trivy scan

- docs/proposals/async-message-listener.md
> $subject
Part of: [#6565](https://github.com/ballerina-platform/ballerina-library/issues/6565)
Related to: [#6508](https://github.com/ballerina-platform/ballerina-library/issues/6508)
N/A
> Add async-listener proposal to the repository

- README.md
> Fix GraalVM badge not properly showing in the README

- .github/workflows/ci.yml
> Skip `master build` for doc changes

- .gitignore
> $subject
Part of: [#6565](https://github.com/ballerina-platform/ballerina-library/issues/6565)
N/A
> Update git-ignore configurations

- README.md
- ballerina/Module.md
- ballerina/Package.md
> $subject
Fixes: [#6600](https://github.com/ballerina-platform/ballerina-library/issues/6600)
N/A
> Add quickstart instructions for ASB listener-svc implementation

- ballerina/Dependencies.toml
- ballerina/admin.bal
- ballerina/caller.bal
- ballerina/init.bal
- ballerina/listener.bal
- ballerina/receiver.bal
- ballerina/sender.bal
- gradle.properties
- native/src/main/java/io/ballerina/lib/asb/admin/AdminNetworkThreadFactory.java
- native/src/main/java/io/ballerina/lib/asb/admin/Administrator.java
- native/src/main/java/io/ballerina/lib/asb/listener/EntityConfig.java
- native/src/main/java/io/ballerina/lib/asb/listener/ErrorConsumer.java
- native/src/main/java/io/ballerina/lib/asb/listener/ListenerConfiguration.java
- native/src/main/java/io/ballerina/lib/asb/listener/MessageConsumer.java
- native/src/main/java/io/ballerina/lib/asb/listener/NativeBServiceAdaptor.java
- native/src/main/java/io/ballerina/lib/asb/listener/NativeCaller.java
- native/src/main/java/io/ballerina/lib/asb/listener/NativeListener.java
- native/src/main/java/io/ballerina/lib/asb/listener/OnErrorCallback.java
- native/src/main/java/io/ballerina/lib/asb/listener/OnMessageAutoCompletableCallback.java
- native/src/main/java/io/ballerina/lib/asb/listener/OnMessageCallback.java
- native/src/main/java/io/ballerina/lib/asb/listener/QueueConfig.java
- native/src/main/java/io/ballerina/lib/asb/listener/TopicConfig.java
- native/src/main/java/io/ballerina/lib/asb/receiver/MessageReceiver.java
- native/src/main/java/io/ballerina/lib/asb/receiver/ReceiverNetworkThreadFactory.java
- native/src/main/java/io/ballerina/lib/asb/sender/MessageSender.java
- native/src/main/java/io/ballerina/lib/asb/sender/SenderNetworkThreadFactory.java
- native/src/main/java/io/ballerina/lib/asb/util/ASBConstants.java
- native/src/main/java/io/ballerina/lib/asb/util/ASBErrorCreator.java
- native/src/main/java/io/ballerina/lib/asb/util/ASBUtils.java
- native/src/main/java/io/ballerina/lib/asb/util/ModuleUtils.java
> $subject
Fixes: [#6604](https://github.com/ballerina-platform/ballerina-library/issues/6604)
N/A
> Update native-package name of the azure-servicebus connector 

- ballerina/Dependencies.toml
- changelog.md
- native/build.gradle
> $subject
Fixes: [#7052](https://github.com/ballerina-platform/ballerina-library/issues/7052)
N/A
> Exclude conflicting JARs from packaging into asb-native JAR

- changelog.md
> Sync changelog after v3.8.2 release

- ballerina/Dependencies.toml
- gradle.properties
> Update lang version and the gradle plugin version

- ballerina/build.gradle
> Remove Java platform version in gradle-plugin configuration

- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/dev-stg-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/trivy-scan.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> [2201.8.x] Upgrade package dependencies

- .gitignore
> Add missing files to gitignore
